package com.packageing.tools.packagetools.entitys;

/*
 * REWRITTEN for the 1.21.1 -> 26.2 update.
 *
 * The original version of this class subclassed raw NMS (net.minecraft.world.entity.decoration.EntityArmorStand)
 * and called obfuscated Mojang-mapped methods directly (e.g. .a(x,y,z,...), .k(boolean), .u(boolean)).
 * That only worked because it was hardcoded against the exact obfuscation of 1.21.1 / CraftBukkit v1_21_R1,
 * which does not exist anymore on 26.2 - obfuscated names are regenerated by Mojang every version.
 *
 * This version is a client-side-only fake entity built on PacketEvents + EntityLib instead, which is the
 * public, version-abstracted way to do the same thing. The public method signatures below are kept
 * IDENTICAL to the old class on purpose, so nothing in thegate.* (GateChevron, IrisPart, CreateGate, the
 * animation classes, TheGateMain) needs to change - EXCEPT getEntityID(), which is now getJavaEntityID()/
 * getBedrockEntityID() (see the twin-entity note below), so the two call sites that used getEntityID()
 * were updated (GatePackages.addEntityID, and the one-off test stand in TheGateMain).
 *
 * TWIN-ENTITY DESIGN (Bedrock compatibility):
 * Bedrock (via Geyser) does not render equipment on an invisible entity at all, and separately cannot
 * render an arbitrary block in an armor stand's head slot under ANY circumstance (Geyser issues #1251 and
 * #2717, both confirmed "Can't Fix" - client-side Bedrock limitations, not something packets can work
 * around). So Bedrock players are always shown a visible-but-textureless stand instead of the clean
 * invisible+equipped look Java gets.
 *
 * An earlier version of this class tried to get ONE shared fake entity to report two different states
 * (invisible for Java, visible for Bedrock) by mutating its metadata per-viewer. That relied on internals
 * of EntityLib's dirty-tracking/packet-building that couldn't be confirmed from the library's public
 * GitHub history, and broke in different ways twice. This version avoids that entirely: EVERY gate part is
 * actually TWO fake entities at the same location - `javaEntity` (always invisible, permanent) and
 * `bedrockEntity` (always visible, permanent). Neither entity's state ever changes based on who's viewing
 * it - each is just the plain, well-supported "one entity, one constant state, N viewers" use case
 * EntityLib is built for. A player is routed to exactly one of the two via BedrockCompat.isBedrock(p) and
 * only ever added as a viewer of that one.
 *
 * NOTE FOR TONY: entity creation, spawn/despawn/teleport, and the ArmorStandMeta pose/rotation setters
 * below are all confirmed against EntityLib's actual source on GitHub (WrapperEntity.java and
 * ArmorStandMeta.java) - not guessed. Equipment goes through raw PacketEvents packets since EntityLib
 * doesn't wrap equipment at all. The three exceptions are setInvisible/setCustomName/setCustomNameVisible,
 * which should live on the base EntityMeta class but I haven't confirmed that file yet - see the comment
 * above setInvisible() below for what to do if those three specifically error out.
 */

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.protocol.entity.type.EntityTypes;
import com.github.retrooper.packetevents.protocol.player.EquipmentSlot;
import com.github.retrooper.packetevents.protocol.player.Equipment;
import com.github.retrooper.packetevents.protocol.world.Location;
import com.github.retrooper.packetevents.util.Vector3f;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment;
import io.github.retrooper.packetevents.util.SpigotConversionUtil;
import me.tofaa.entitylib.meta.other.ArmorStandMeta;
import me.tofaa.entitylib.wrapper.WrapperEntity;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;

public class ArmorStand {

    // Java-facing twin: always invisible (equipment still renders floating on Java - no Bedrock limitation there).
    private final WrapperEntity javaEntity;
    private final ArmorStandMeta javaMeta;

    // Bedrock-facing twin: always visible, forced permanently in the constructor below and never toggled -
    // there is no per-viewer state to manage here at all, which is the whole point of the twin design.
    private final WrapperEntity bedrockEntity;
    private final ArmorStandMeta bedrockMeta;

    private float bodyRotation = 0.0f;
    private double locationX = 0.0;
    private double locationY = 0.0;
    private double locationZ = 0.0;
    private float headX = 0.0f;
    private float headY = 0.0f;
    private float headZ = 0.0f;

    private ItemStack headMaterial = null;
    private ItemStack mainHand = null;
    private ItemStack offHand = null;
    private ItemStack bodyArmor = null;
    private ItemStack legArmor = null;
    private ItemStack feetArmor = null;

    private ArmorStand(WrapperEntity javaEntity, WrapperEntity bedrockEntity) {
        this.javaEntity = javaEntity;
        this.javaMeta = (ArmorStandMeta) javaEntity.getEntityMeta();
        this.bedrockEntity = bedrockEntity;
        this.bedrockMeta = (ArmorStandMeta) bedrockEntity.getEntityMeta();
        this.bedrockMeta.setInvisible(false); // permanent - see class-level note. Never touched again after this.
    }

    public static ArmorStand CreateArmorStand(org.bukkit.Location location, float headRotationX, float headRotationY, float headRotationZ, float rotBody) {
        WrapperEntity javaWrapper = new WrapperEntity(EntityTypes.ARMOR_STAND);
        WrapperEntity bedrockWrapper = new WrapperEntity(EntityTypes.ARMOR_STAND);
        ArmorStand astand = new ArmorStand(javaWrapper, bedrockWrapper);
        astand.bodyRotation = rotBody;
        astand.setLocation(location.getX(), location.getY(), location.getZ());
        astand.setCustomNameVisible(false);
        astand.setHeadRotation(headRotationX, headRotationY, headRotationZ);
        astand.setSmall(false);
        astand.setInvisible(true); // only ever affects javaEntity - bedrockEntity was already forced visible above
        astand.setHasBasePlate(false);

        Location peLoc = new Location(location.getX(), location.getY(), location.getZ(), rotBody, 0.0f);
        javaWrapper.spawn(peLoc);
        bedrockWrapper.spawn(peLoc);

        return astand;
    }

    /** Sends the spawn + equipment + metadata packets to one player. Replaces PackageManager.SendSpawnPackage. */
    public void showTo(Player p) {
        WrapperEntity target = BedrockCompat.isBedrock(p) ? this.bedrockEntity : this.javaEntity;
        target.addViewer(p.getUniqueId());
        this.pushEquipment(p, target);
        target.refresh();
    }

    /** Removes this fake entity from one player's client. Replaces PackageManager.SendDespawnPackage. */
    public void hideFrom(Player p) {
        WrapperEntity target = BedrockCompat.isBedrock(p) ? this.bedrockEntity : this.javaEntity;
        target.removeViewer(p.getUniqueId());
    }

    /** Re-sends equipment + metadata to a player who can already see this entity. Replaces PackageManager.SendUpdate. */
    public void updateFor(Player p) {
        WrapperEntity target = BedrockCompat.isBedrock(p) ? this.bedrockEntity : this.javaEntity;
        this.pushEquipment(p, target);
        target.refresh();
    }

    /**
     * Moves the entity and re-sends metadata + a teleport packet. Replaces PackageManager.SendTeleport.
     * Note: the `p` parameter has always been unused here (kept only for call-site compatibility) - location
     * is not a per-viewer thing, so both twins move together regardless of who's asking.
     */
    public void teleportFor(Player p) {
        this.javaEntity.refresh();
        this.bedrockEntity.refresh();
        Location peLoc = new Location(this.locationX, this.locationY, this.locationZ, this.bodyRotation, 0.0f);
        this.javaEntity.teleport(peLoc);
        this.bedrockEntity.teleport(peLoc);
    }

    /*
     * EntityLib does not wrap entity equipment at all (confirmed by reading its WrapperEntity.java source -
     * no equipment method exists). So equipment goes out as a raw PacketEvents packet instead. Bukkit
     * ItemStacks have to be converted to PacketEvents' own internal ItemStack type first via
     * SpigotConversionUtil - PacketEvents' internal ItemStack has a private constructor as of 2.11+,
     * so this conversion call isn't optional.
     */
    private void pushEquipment(Player p, WrapperEntity target) {
        List<Equipment> equipmentList = new ArrayList<>();
        if (this.mainHand != null) equipmentList.add(new Equipment(EquipmentSlot.MAIN_HAND, SpigotConversionUtil.fromBukkitItemStack(this.mainHand)));
        if (this.offHand != null) equipmentList.add(new Equipment(EquipmentSlot.OFF_HAND, SpigotConversionUtil.fromBukkitItemStack(this.offHand)));
        if (this.feetArmor != null) equipmentList.add(new Equipment(EquipmentSlot.BOOTS, SpigotConversionUtil.fromBukkitItemStack(this.feetArmor)));
        if (this.legArmor != null) equipmentList.add(new Equipment(EquipmentSlot.LEGGINGS, SpigotConversionUtil.fromBukkitItemStack(this.legArmor)));
        if (this.bodyArmor != null) equipmentList.add(new Equipment(EquipmentSlot.CHEST_PLATE, SpigotConversionUtil.fromBukkitItemStack(this.bodyArmor)));
        ItemStack head = this.headMaterial != null ? this.headMaterial : new ItemStack(Material.AIR);
        // Bedrock cannot render an arbitrary block in the head slot at all (confirmed unfixable Geyser
        // limitation - see the class-level note above). If this exact material has a texture configured in
        // BedrockHeadTextures, swap in a custom-textured skull for the Bedrock twin only; Java keeps the
        // plain block either way, and anything not covered in config just falls back to the plain block on
        // Bedrock too (today's textureless-but-visible behavior).
        if (target == this.bedrockEntity && head.getType() != Material.AIR) {
            String textureValue = thegate.main.Globals.BedrockHeadTextures.get(head.getType());
            if (textureValue != null) {
                head = HeadTextureFactory.build(textureValue);
            }
        }
        equipmentList.add(new Equipment(EquipmentSlot.HELMET, SpigotConversionUtil.fromBukkitItemStack(head)));

        WrapperPlayServerEntityEquipment packet = new WrapperPlayServerEntityEquipment(target.getEntityId(), equipmentList);
        PacketEvents.getAPI().getPlayerManager().sendPacket(p, packet);
    }

    public void setHeadRotation(float x, float y, float z) {
        this.headX = x;
        this.headY = y;
        this.headZ = z;
        this.javaMeta.setHeadRotation(new Vector3f(x, y, z));
        this.bedrockMeta.setHeadRotation(new Vector3f(x, y, z));
    }

    public void setLocation(double x, double y, double z) {
        this.locationX = x;
        this.locationY = y;
        this.locationZ = z;
        Location peLoc = new Location(x, y, z, this.bodyRotation, 0.0f);
        this.javaEntity.teleport(peLoc);
        this.bedrockEntity.teleport(peLoc);
    }

    public void setCustomName(String text) {
        this.javaMeta.setCustomName(net.kyori.adventure.text.Component.text(text));
        this.bedrockMeta.setCustomName(net.kyori.adventure.text.Component.text(text));
    }

    public void setCustomNameVisible(boolean visible) {
        this.javaMeta.setCustomNameVisible(visible);
        this.bedrockMeta.setCustomNameVisible(visible);
    }

    public double getLocationX() { return this.locationX; }
    public double getLocationY() { return this.locationY; }
    public double getLocationZ() { return this.locationZ; }

    public org.bukkit.util.Vector getLocationVector() {
        return new org.bukkit.util.Vector(this.locationX, this.locationY, this.locationZ);
    }

    public void setSmall(boolean isSmall) {
        this.javaMeta.setSmall(isSmall);
        this.bedrockMeta.setSmall(isSmall);
    }

    public void setHasBasePlate(boolean hasBasePlate) {
        this.javaMeta.setHasNoBasePlate(!hasBasePlate);
        this.bedrockMeta.setHasNoBasePlate(!hasBasePlate);
    }

    public void SetShowArms(boolean showarms) {
        this.javaMeta.setHasArms(showarms);
        this.bedrockMeta.setHasArms(showarms);
    }

    public void setNoGravity(boolean noGravity) {
        this.javaEntity.setHasNoGravity(noGravity);
        this.bedrockEntity.setHasNoGravity(noGravity);
    }

    /*
     * setInvisible/setCustomName/setCustomNameVisible below are still an educated guess - they should live
     * on the base me.tofaa.entitylib.meta.EntityMeta class (every entity has these), but I haven't been able
     * to confirm the exact method names against that file yet the way I did for ArmorStandMeta/WrapperEntity.
     * If mvn package errors on these three specifically, grab me the source of
     * api/src/main/java/me/tofaa/entitylib/meta/EntityMeta.java the same way you did for the other two files
     * and I'll fix them the same way.
     *
     * This ONLY ever applies to javaEntity now - bedrockEntity's meta was permanently forced to visible in
     * the constructor and must never be touched again, by design (see the class-level twin-entity note).
     */
    public void setInvisible(boolean isInvisible) { this.javaMeta.setInvisible(isInvisible); }

    public float getHeadX() { return this.headX; }
    public float getHeadY() { return this.headY; }
    public float getHeadZ() { return this.headZ; }
    public org.bukkit.util.Vector getHeadVector() { return new org.bukkit.util.Vector(this.headX, this.headY, this.headZ); }

    public float getBodyRotation() { return this.bodyRotation; }
    public void setBodyRotation(float bodyRotation) {
        this.bodyRotation = bodyRotation;
        this.setLocation(this.locationX, this.locationY, this.locationZ);
    }

    public ItemStack getHeadMaterial() { return this.headMaterial; }
    public void setHeadMaterial(ItemStack headMaterial) { this.headMaterial = headMaterial; }

    public ItemStack getMainHand() { return this.mainHand; }
    public void setMainHand(ItemStack mainHand) { this.mainHand = mainHand; }

    public ItemStack getOffHand() { return this.offHand; }
    public void setOffHand(ItemStack offHand) { this.offHand = offHand; }

    public ItemStack getBodyArmor() { return this.bodyArmor; }
    public void setBodyArmor(ItemStack bodyArmor) { this.bodyArmor = bodyArmor; }

    public ItemStack getLegArmor() { return this.legArmor; }
    public void setLegArmor(ItemStack legArmor) { this.legArmor = legArmor; }

    public ItemStack getFeetArmor() { return this.feetArmor; }
    public void setFeetArmor(ItemStack feetArmor) { this.feetArmor = feetArmor; }

    /**
     * Two IDs now, one per twin - see the class-level twin-entity note. Call sites that used to collect a
     * single getEntityID() (GatePackages.addEntityID, and the one-off test stand in TheGateMain) now collect
     * BOTH. This is safe everywhere those IDs are later used for despawn-by-ID (GateObject.Vanish,
     * WooshAnimation.Remove): those loops just call removeViewer(uuid) for every ID in the list, which is a
     * harmless no-op for whichever twin that particular player was never viewing.
     */
    public int getJavaEntityID() { return this.javaEntity.getEntityId(); }
    public int getBedrockEntityID() { return this.bedrockEntity.getEntityId(); }

    public void remove() {
        this.javaEntity.remove();
        this.bedrockEntity.remove();
    }
}
