package com.packageing.tools.packagetools.entitys;

/*
 * REWRITTEN for the 1.21.1 -> 26.2 update.
 *
 * The original version of this class subclassed raw NMS (net.minecraft.world.entity.decoration.EntityArmorStand)
 * and called obfuscated Mojang-mapped methods directly (e.g. .a(x,y,z,...), .k(boolean), .u(boolean)).
 * That only worked because it was hardcoded against the exact obfuscation of 1.21.1 / CraftBukkit v1_21_R1,
 * which does not exist anymore on 26.2 - obfuscated names are regenerated by Mojang every version.
 *
 * This version is a client-side-only fake entity built on PacketEvents + EntityLib instead, which is the
 * public, version-abstracted way to do the same thing. The public method signatures below are kept
 * IDENTICAL to the old class on purpose, so nothing in thegate.* (GatePackages, GateChevron, IrisPart,
 * CreateGate, the animation classes, TheGateMain) needs to change.
 *
 * NOTE FOR TONY: entity creation, spawn/despawn/teleport, and the ArmorStandMeta pose/rotation setters
 * below are all confirmed against EntityLib's actual source on GitHub (WrapperEntity.java and
 * ArmorStandMeta.java) - not guessed. Equipment goes through raw PacketEvents packets since EntityLib
 * doesn't wrap equipment at all. The three exceptions are setInvisible/setCustomName/setCustomNameVisible,
 * which should live on the base EntityMeta class but I haven't confirmed that file yet - see the comment
 * above setInvisible() below for what to do if those three specifically error out.
 */

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.protocol.entity.type.EntityTypes;
import com.github.retrooper.packetevents.protocol.player.EquipmentSlot;
import com.github.retrooper.packetevents.protocol.player.Equipment;
import com.github.retrooper.packetevents.protocol.world.Location;
import com.github.retrooper.packetevents.util.Vector3f;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment;
import io.github.retrooper.packetevents.util.SpigotConversionUtil;
import me.tofaa.entitylib.meta.other.ArmorStandMeta;
import me.tofaa.entitylib.wrapper.WrapperEntity;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;

public class ArmorStand {

    private final WrapperEntity entity;
    private final ArmorStandMeta meta;

    private float bodyRotation = 0.0f;
    private double locationX = 0.0;
    private double locationY = 0.0;
    private double locationZ = 0.0;
    private float headX = 0.0f;
    private float headY = 0.0f;
    private float headZ = 0.0f;

    private ItemStack headMaterial = null;
    private ItemStack mainHand = null;
    private ItemStack offHand = null;
    private ItemStack bodyArmor = null;
    private ItemStack legArmor = null;
    private ItemStack feetArmor = null;

    private ArmorStand(WrapperEntity entity) {
        this.entity = entity;
        this.meta = (ArmorStandMeta) entity.getEntityMeta();
    }

    public static ArmorStand CreateArmorStand(org.bukkit.Location location, float headRotationX, float headRotationY, float headRotationZ, float rotBody) {
        WrapperEntity wrapperEntity = new WrapperEntity(EntityTypes.ARMOR_STAND);
        ArmorStand astand = new ArmorStand(wrapperEntity);
        astand.bodyRotation = rotBody;
        astand.setLocation(location.getX(), location.getY(), location.getZ());
        astand.setCustomNameVisible(false);
        astand.setHeadRotation(headRotationX, headRotationY, headRotationZ);
        astand.setSmall(false);
        astand.setInvisible(true);
        astand.setHasBasePlate(false);

        Location peLoc = new Location(location.getX(), location.getY(), location.getZ(), rotBody, 0.0f);
        wrapperEntity.spawn(peLoc);

        return astand;
    }

    /** Sends the spawn + equipment + metadata packets to one player. Replaces PackageManager.SendSpawnPackage. */
    public void showTo(Player p) {
        this.entity.addViewer(p.getUniqueId());
        this.pushEquipment(p);
        this.pushMeta();
    }

    /** Removes this fake entity from one player's client. Replaces PackageManager.SendDespawnPackage. */
    public void hideFrom(Player p) {
        this.entity.removeViewer(p.getUniqueId());
    }

    /** Re-sends equipment + metadata to a player who can already see this entity. Replaces PackageManager.SendUpdate. */
    public void updateFor(Player p) {
        this.pushEquipment(p);
        this.pushMeta();
    }

    /** Moves the entity and re-sends metadata + a teleport packet. Replaces PackageManager.SendTeleport. */
    public void teleportFor(Player p) {
        this.pushMeta();
        this.entity.teleport(new Location(this.locationX, this.locationY, this.locationZ, this.bodyRotation, 0.0f));
    }

    private void pushMeta() {
        // WrapperEntity#refresh() sends the current metadata (built from the ArmorStandMeta setters below) to viewers.
        this.entity.refresh();
    }

    /*
     * EntityLib does not wrap entity equipment at all (confirmed by reading its WrapperEntity.java source -
     * no equipment method exists). So equipment goes out as a raw PacketEvents packet instead. Bukkit
     * ItemStacks have to be converted to PacketEvents' own internal ItemStack type first via
     * SpigotConversionUtil - PacketEvents' internal ItemStack has a private constructor as of 2.11+,
     * so this conversion call isn't optional.
     */
    private void pushEquipment(Player p) {
        List<Equipment> equipmentList = new ArrayList<>();
        if (this.mainHand != null) equipmentList.add(new Equipment(EquipmentSlot.MAIN_HAND, SpigotConversionUtil.fromBukkitItemStack(this.mainHand)));
        if (this.offHand != null) equipmentList.add(new Equipment(EquipmentSlot.OFF_HAND, SpigotConversionUtil.fromBukkitItemStack(this.offHand)));
        if (this.feetArmor != null) equipmentList.add(new Equipment(EquipmentSlot.BOOTS, SpigotConversionUtil.fromBukkitItemStack(this.feetArmor)));
        if (this.legArmor != null) equipmentList.add(new Equipment(EquipmentSlot.LEGGINGS, SpigotConversionUtil.fromBukkitItemStack(this.legArmor)));
        if (this.bodyArmor != null) equipmentList.add(new Equipment(EquipmentSlot.CHEST_PLATE, SpigotConversionUtil.fromBukkitItemStack(this.bodyArmor)));
        ItemStack head = this.headMaterial != null ? this.headMaterial : new ItemStack(Material.AIR);
        equipmentList.add(new Equipment(EquipmentSlot.HELMET, SpigotConversionUtil.fromBukkitItemStack(head)));

        WrapperPlayServerEntityEquipment packet = new WrapperPlayServerEntityEquipment(this.entity.getEntityId(), equipmentList);
        PacketEvents.getAPI().getPlayerManager().sendPacket(p, packet);
    }

    public void setHeadRotation(float x, float y, float z) {
        this.headX = x;
        this.headY = y;
        this.headZ = z;
        this.meta.setHeadRotation(new Vector3f(x, y, z));
    }

    public void setLocation(double x, double y, double z) {
        this.locationX = x;
        this.locationY = y;
        this.locationZ = z;
        this.entity.teleport(new Location(x, y, z, this.bodyRotation, 0.0f));
    }

    public void setCustomName(String text) {
        this.meta.setCustomName(net.kyori.adventure.text.Component.text(text));
    }

    public void setCustomNameVisible(boolean visible) {
        this.meta.setCustomNameVisible(visible);
    }

    public double getLocationX() { return this.locationX; }
    public double getLocationY() { return this.locationY; }
    public double getLocationZ() { return this.locationZ; }

    public org.bukkit.util.Vector getLocationVector() {
        return new org.bukkit.util.Vector(this.locationX, this.locationY, this.locationZ);
    }

    public void setSmall(boolean isSmall) { this.meta.setSmall(isSmall); }
    public void setHasBasePlate(boolean hasBasePlate) { this.meta.setHasNoBasePlate(!hasBasePlate); }
    public void SetShowArms(boolean showarms) { this.meta.setHasArms(showarms); }
    public void setNoGravity(boolean noGravity) { this.entity.setHasNoGravity(noGravity); }
    /*
     * setInvisible/setCustomName/setCustomNameVisible below are still an educated guess - they should live
     * on the base me.tofaa.entitylib.meta.EntityMeta class (every entity has these), but I haven't been able
     * to confirm the exact method names against that file yet the way I did for ArmorStandMeta/WrapperEntity.
     * If mvn package errors on these three specifically, grab me the source of
     * api/src/main/java/me/tofaa/entitylib/meta/EntityMeta.java the same way you did for the other two files
     * and I'll fix them the same way.
     */
    public void setInvisible(boolean isInvisible) { this.meta.setInvisible(isInvisible); }

    public float getHeadX() { return this.headX; }
    public float getHeadY() { return this.headY; }
    public float getHeadZ() { return this.headZ; }
    public org.bukkit.util.Vector getHeadVector() { return new org.bukkit.util.Vector(this.headX, this.headY, this.headZ); }

    public float getBodyRotation() { return this.bodyRotation; }
    public void setBodyRotation(float bodyRotation) {
        this.bodyRotation = bodyRotation;
        this.setLocation(this.locationX, this.locationY, this.locationZ);
    }

    public ItemStack getHeadMaterial() { return this.headMaterial; }
    public void setHeadMaterial(ItemStack headMaterial) { this.headMaterial = headMaterial; }

    public ItemStack getMainHand() { return this.mainHand; }
    public void setMainHand(ItemStack mainHand) { this.mainHand = mainHand; }

    public ItemStack getOffHand() { return this.offHand; }
    public void setOffHand(ItemStack offHand) { this.offHand = offHand; }

    public ItemStack getBodyArmor() { return this.bodyArmor; }
    public void setBodyArmor(ItemStack bodyArmor) { this.bodyArmor = bodyArmor; }

    public ItemStack getLegArmor() { return this.legArmor; }
    public void setLegArmor(ItemStack legArmor) { this.legArmor = legArmor; }

    public ItemStack getFeetArmor() { return this.feetArmor; }
    public void setFeetArmor(ItemStack feetArmor) { this.feetArmor = feetArmor; }

    public int getEntityID() { return this.entity.getEntityId(); }

    public void remove() { this.entity.remove(); }

    /** package-visible so PackageManager (the thin static facade kept for call-site compatibility) can reach it */
    WrapperEntity getWrapperEntity() { return this.entity; }
}
